### PR TITLE
Update jspsych.js - adding mobile browser detection for exclusions

### PR DESCRIPTION
**Pull request by celstark**
Using the regexp from the open-source http://detectmobilebrowsers.com, I've added an exclusions.nomobile option.  Set to true exclude phones.  This can be elaborated on to also exclude tablets.

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Great idea. 

On the website it says the regex was last updated in 2014. Is it up to the task of reliably identifying modern mobile browsers?

It looks like the PR also contains a couple plugins. Can those be separated out?

**Comment by becky-gilbert** [comment]
Hi @celstark, thanks for putting this mobile device detection feature together, and sorry for the delay getting to this. It'd be great to add it to the next release. Just wanted to follow-up on Josh's questions about whether you can separate out the plugin code that's included in this pull request, and if you know whether this particular regex is up-to-date enough to use?

**Comment by becky-gilbert** [comment]
Marking this for the 7.0 release so that we can look into the most up-to-date regex for mobile devices.

**Comment by jodeleeuw** [comment]
I'm going to close this PR since the regex is old. I'll open a separate issue for mobile detection, but note that the screen width/height exclusions can serve that purpose if the goal is to avoid small screens. Adding a keyboard-response trial also ensures that the participant has a physical keyboard before progressing.

**Pull request closed without merging**
