### PR TITLE
Add jsPsych Builder reference to docs

### PR DESCRIPTION
**Pull request by bjoluc**
Here's my approach to #1855. As I started writing, I noticed a separate section on the overview/running-experiments page would be a bit overkill. Hence, here's only a little info box on that page, and an additional sentence in the hello-world tutorial introduction. Also, there's not really a need for a separate jsPsych Builder hello-world tutorial, as `jspsych init` does it all. Users can simply start with the demo experiment tutorial which I also refer to in the jsPsych Builder readme.

### CODE REVIEW

**Comment by becky-gilbert** [comment]
Thanks very much for this @bjoluc! I might make some very minor edits, but overall I think this looks great! If I do make any changes, I'll post the commit here so that you can comment (I realize there was probably a way for me to edit via the pull request before merging, but this seemed easier...).

**Comment by becky-gilbert** [comment]
Ok, you can see my edits [here](https://github.com/jspsych/jsPsych/commit/d5efdb301e512747f29af0a00e5a3f345e448a4e). I put the jsPsych Builder reference into an info box on the hello world page as well, because I wanted to say a bit more about it and point out that people might want to do the jsPsych Builder stuff alongside jsPsych's Hello World. Let me know if you want to suggest any changes.

**Comment by bjoluc** [comment]
Thanks for the edits @becky-gilbert, they make a lot of sense! One minor thing I do not fully understand is the "alongside this Hello World tutorial" part: Do you mean people should do the manual setup and the jsPsych Builder setup alongside each other? Since the Hello World tutorial is really just the steps that jsPsych Builder makes obsolete, I could even imagine writing "in place of this Hello World tutorial". But I may as well be missing something here. What do you think?

**Comment by becky-gilbert** [comment]
Ah yes, you're right. I was thinking that people who are totally new to jsPsych would need to switch back to the jsPsych hello world tutorial at the point where you mention [writing experiments](https://github.com/bjoluc/jspsych-builder#writing-experiments), because I didn't see a code snippet with the construction of a jsPsych trial/timeline anywhere. But now I see that you've linked to part of the code from the RT task tutorial. I'll update the docs text as you suggest 👍

**Comment by becky-gilbert** [comment]
@jodeleeuw not urgent, but you might want to have a look at the info admonitions that we've added about jsPsych Builder in the docs, to make sure you're happy with them.
* [Hello world page](https://github.com/jspsych/jsPsych/blame/master/docs/tutorials/hello-world.md#L5-L6)
* [Running experiments page](https://github.com/jspsych/jsPsych/blame/master/docs/overview/running-experiments.md#L11-L14)

**Pull request merged**
