### PR TITLE
Merges minimum valid RT changes into master

### PR DESCRIPTION
**Pull request by jodeleeuw**
See #546 for origin. Had to move into this branch to do some testing work prior to pulling into master.

@becky-gilbert can you update the docs for this change and then merge once everything is in place? In the docs we should note that this only applies to *keyboard* response times. Maybe in a future version we could figure out how to apply it to button presses too.

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Oh wait, it looks like this messes up a whole lot of tests. Will need to figure out what is going on.

**Comment by jodeleeuw** [comment]
OK, this should be fine now! @becky-gilbert go ahead and merge when ready.

**Comment by becky-gilbert** [comment]
Thanks @jodeleeuw! I hadn't merged this one yet because I couldn't figure out why all of the tests were failing before - just saw the problem and fix in your commit. 

I'll merge and add this to the docs.

**Comment by becky-gilbert** [comment]
@jodeleeuw happy for me to delete the min-rt branch?

**Comment by jodeleeuw** [comment]
yep!

**Pull request merged**
