### PR TITLE
add render_on_canvas option, fix maintain_aspect_ratio - #891 #969 #1172

### PR DESCRIPTION
**Pull request by becky-gilbert**
Adds `render_on_canvas` option to all image-* plugins, the animation plugin, and the categorize-animation plugin. This is to fix the problem with brief blank screens (white flashes) between consecutive images when they are first shown in Firefox and Edge when (#891, #969). Setting `render_on_canvas` to `true` (the default) fixes this problem, and setting it to `false` presents the image(s) in an img element, as before.

Also fixes bug with `maintain_aspect_ratio` in the image-* plugins (#1172). Now when only one image dimension is specified and `maintain_aspect_ratio` is `false`, the unspecified dimension will be the image's original dimension, and the image will stretch or compress.

Includes all docs updates and updated example files.

Tested on Firefox, Chrome and Edge.

### CODE REVIEW

**Comment by becky-gilbert** [comment]
@jodeleeuw it might be tricky to set up tests for the image canvas rendering option because [I don't think Jest supports canvas/context functions](https://stackoverflow.com/questions/33269093/how-to-add-canvas-support-to-my-tests-in-jest). But it looks like it's possible to add in support (see [here](https://github.com/jsdom/jsdom#canvas-support)) or mock it (see [here](https://www.npmjs.com/package/jest-canvas-mock)). I'm happy to try to set up a way of testing the canvas rendering, but wasn't sure if you want to suggest a method? Or maybe you're trying to avoid dependencies in your test set up?

Most of the tests pass when I add `render_on_canvas: false` to the test trial set up. But this one in plugin-image-button-response.test.js is still not passing:
```javascript
test('prompt should append below button', function(){
  var trial = {
    type: 'image-button-response',
    stimulus: '../media/blue.png',
    choices: ['button-choice'],
    prompt: '<p>This is a prompt</p>',
    render_on_canvas: false
  }

  jsPsych.init({
    timeline: [trial],
    auto_preload: false
  });

  expect(jsPsych.getDisplayElement().innerHTML).toMatch('<button class=\"jspsych-btn\">button-choice</button></div></div><p>This is a prompt</p>');
});
```
It fails because the display element also contains the &lt;img> before the button and prompt, and because I put the prompt inside of a &lt;div> for consistency with the canvas version. So some parts of the string matched the expected string above. The additional stuff is in bold below:

> Received string:    **"&lt;img src=\"../media/blue.png\" id=\"jspsych-image-button-response-stimulus\" style=\"height: 0px; width: 0px;\">&lt;div id=\"jspsych-image-button-response-btngroup\">&lt;div class=\"jspsych-image-button-response-button\" style=\"display: inline-block; margin:0px 8px\" id=\"jspsych-image-button-response-button-0\" data-choice=\"0\">**&lt;button class=\"jspsych-btn\">button-choice&lt;/button>&lt;/div>&lt;/div>**&lt;div**>&lt;p>This is a prompt&lt;/p>**&lt;/div>**"

So I'm sure how this test was passing before my canvas plugin changes, because I would've thought that the &lt;img> element, btngroup div, and button response div would be in the DOM with the current plugin version too. I tried reproducing this with an image-button-response example that included `auto_preload: false` in `jsPsych.init` but I get the image and btngroup/button divs in the DOM.

**Comment by jodeleeuw** [comment]
> So I'm not sure how this test was passing before my canvas plugin changes, because I would've thought that the  element, btngroup div, and button response div would be in the DOM with the current plugin version too.

I was confused about this too, but then I remembered that `toMatch` is different than `toEqual` and accepts substrings. So it matches because the substring was found inside the `.innerHTML`. I think it is broken now because of the added `<div>`. I don't mind adding the `<div>` if that's consistent with other plugins. I think most `prompt` parameters don't add one, but I'm not sure?

**Comment by becky-gilbert** [comment]
Ahh. Thanks for explaining. And sorry, I should've looked at the docs for `toMatch`!

You're right - most plugins don't put the `prompt` inside a `<div>`. I added one to these plugins so that, with `render_on_canvas: true`, I could add the prompt by appending a new div to the DOM (to avoid adding the prompt by modifying `display_element.innerHTML`, which I think is [less efficient](https://medium.com/@kevinchi118/innerhtml-vs-createelement-appendchild-3da39275a694)):
```javascript
if (trial.prompt !== null) {
  var prompt_div = document.createElement("div");
  prompt_div.innerHTML = trial.prompt;
  display_element.insertBefore(prompt_div, btngroup_div.nextElementSibling);
}
```
Then I also put the prompt in a `<div>` with `render_on_canvas: false` so that the structure is consistent within the plugin.

But I can definitely remove the prompt `<div>` with `render_on_canvas: false` for consistency with other plugins. And with `render_on_canvas: true`, I'll check that adding the prompt with `innerHTML` doesn't cause problems, in which case I can switch from the createElement/insertBefore method above to `display_element.innerHTML += trial.prompt` 👍

**Comment by jodeleeuw** [comment]
if `.innerHTML +=` fails you can use `insertAdjacentHTML()` instead ([docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML)). It's almost the same functionality, but it doesn't redraw the whole document.

**Comment by jodeleeuw** [comment]
As for canvas testing, I'd say let's not worry too much about that. We don't have robust tests for most plugins yet, and it's not the highest priority right now given that we have the examples folder as a kind of non-automated test suite. But, if adding canvas testing support via an extension is easy that's fine with me!

**Pull request merged**
