### PR TITLE
Added very simple alternative jspsych-survey-html-form plugin

### PR DESCRIPTION
**Pull request by jansim**
Hello,
for a study I'm currently working on, I created this super simple version of a form plugin. I saw, that there's already a planned form plugin in the works #135 , but maybe this is still useful as a starting point or so. This plugin simply renders an HTML string containing the input elements for the form and parses them using a vanilla JS version of jQuery's serializeArray().

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Thanks! This can be a great intermediate option until the other version is ready. Are you willing to write the documentation and tests for the plugin?

**Comment by jansim** [comment]
I added a a test & basic documentation for the plugin :+1: 

Also, is there a particular reason why data in the `jspsych-survey-text` plugin is passed as JSON-text and not as a JS object? Currently this plugin mirrors the behavior since I based it off of the survey-test plugin, but I could easily remove this.

**Comment by jodeleeuw** [comment]
Thanks again. This is a really versatile plugin!

I made one small functional change in the merged version: I encoded the data as a JSON string instead of an object. While objects are more useful, the current design is that anything encoded in the data is a primitive type. This might be worth revisiting in the future, but I wanted to maintain consistency across plugins for now.

**Comment by jansim** [comment]
Ah ok, that makes sense! Thanks for merging the PR.

**Pull request merged**
