### PR TITLE
RDK and visual-search-circle plugins: parameter type changes - fixes #2132, #2139

### LINKED ISSUE #2132: change plugin parameters: option of different types to a single type
With the switch to TypeScript in v7.0, plugin parameters that allow different types are trickier to deal with (see discussion [here](https://github.com/jspsych/jsPsych/pull/2078#discussion_r692059043)). One solution is to enforce a single type* for these parameters. This will be a breaking change for the affected plugins, and will require changes to the documentation, as well as any demo code and example files that use the parameter type that is no longer allowed. 

Affected plugins and parameters:
* RDK `correct_choice`: currently can be a string or array. Change to array.
* visual-search-circle `foil`: currently can be a string or array. Change to array.

I scanned the plugin docs and didn't catch any others.

\* Another solution is to create a new 'any' type for these parameters, but the downside is that we will lose the benefit of type-safety in these cases.

### PR DESCRIPTION
**Pull request by becky-gilbert**
This `modularization-plugin-param-type-changes` branch is based off `modularization-plugins`. It implements some breaking parameter type changes to the RDK and visual-search-plugins - see #2132. The parameter type changes required additional changes to the plugin's `trial` methods, plugin docs, and example files (all included).

This PR is set up with `modularization` as the base branch, and shouldn't be merged until `modularization-plugins` is merged into `modularization`. I've separated these changes from `modularization-plugins` because that branch will be squash-merged, and I didn't want to lose track of these plugin-specific breaking changes. (Though I'm now realizing that I may have made this unnecessarily complicated... sorry!).

### CODE REVIEW

**Comment by becky-gilbert** [comment]
This PR will now include the changes to the `visual-search-circle` plugin discussed in #2139. This includes changing the `foil` parameter to a single type (as discussed in #2132, except it will now be a string rather than array), while also adding a new `stimuli` parameter to allow image arrays.

**Comment by jodeleeuw** [comment]
@becky-gilbert I was working on merging `modularization` into this branch so that the PR was up to date, but I realized you may have lingering changes related to the `foil` parameter. Do you have anything that's not pushed that you're doing?

**Comment by becky-gilbert** [comment]
I actually did that locally and haven't pushed yet. I'll push ASAP.

**Comment by becky-gilbert** [comment]
@jodeleeuw I think this is ready to merge into `modularization` now, if you're happy with the changes? I've just merged the recent `modularization` updates into this branch and fixed the merge conflicts.
I'm not sure how to clean up the commits on this PR - rebase and merge?

**Comment by bjoluc** [comment]
> I'm not sure how to clean up the commits on this PR - rebase and merge?
I did an interactive rebase locally since there were a number of conflicts during rebasing. Most times, in complicated situations like these, it is way easier to just squash-merge and edit the commit message accordingly. Interactively rebasing large PRs requires a good amount of time, care and awareness.

**Comment by bjoluc** [comment]
Whoopsie, it looks like you pushed all the old commits again @becky-gilbert – I think you didn't pull after I did the interactive rebase. I still have the commits locally; shall I force-push them again and you quickly replicate the two last commits on top of them?

**Comment by becky-gilbert** [comment]
FYI, `rdk`-related files have been deleted from `modularization-plugin-param-type-changes`, and the `rdk` changes discussed here will be copied into the `rdk` files in the `jspsych-contrib` repo. 

So now this PR just contains the `visual-search-circle` changes.

**Comment by becky-gilbert** [comment]
> Whoopsie, it looks like you pushed all the old commits again @becky-gilbert – I think you didn't pull after I did the interactive rebase. I still have the commits locally; shall I force-push them again and you quickly replicate the two last commits on top of them?

ARGH!! 😫 Sorry. Yes please fix it again! So after you force-push, then if I just do a `git pull`, replicate my last two commits and push, it should work?

**Comment by bjoluc** [comment]
No probs at all!
> So after you force-push, then if I just do a `git pull`, replicate my last two commits and push, it should work?

Exactly, no big deal. `git pull` should force-pull automatically (if I remember correctly). If it doesn't, just use `git pull --force origin modularization-plugin-param-type-changes` instead.

**Comment by becky-gilbert** [comment]
@bjoluc ok I give up 😩 Feel free to do yet another force-push and then I won't update this branch again. We can just handle the `rdk` merge conflicts when this branch gets merged into `modularization` or when `modularization-new-docs` is merged into `modularization`.

**Comment by bjoluc** [comment]
@becky-gilbert Oh no :see_no_evil: I guess I lied to you about the auto force pull thing; now both sets of commits are there. I'll just cherry-pick your latest commits onto my local branch now. Sorry!

**Comment by bjoluc** [comment]
@becky-gilbert Done, should be ready now. (If you'd like to change anything still, `git pull --force origin modularization-plugin-param-type-changes` should do the trick!)

**Pull request merged**
