### PR TITLE
Makes jsPsych an exportable module

### PR DESCRIPTION
**Pull request by RobAWilkinson**
Picked up where #482  left off, and cleaned up the tests to work, took advantage of the fact that jest has built in jsDOM functionality.

My thought going forward, is to have all the plugins in folders, with `package.json` and `main.js` and make them exportable as well. That way users can follow semver and use only specific versions of a plugin.

I'm using this fork successfully in a React project like so:
```
import jspsych from 'jspsych';
window.jsPsych = jspsych;
import 'jspsych/plugins/jspsych-audio-button-response.js';
import 'jspsych/plugins/jspsych-audio-keyboard-response.js';
import 'jspsych/plugins/jspsych-call-function.js';
import 'jspsych/plugins/jspsych-survey-likert.js';
import 'jspsych/plugins/jspsych-survey-multi-choice.js';
import 'jspsych/plugins/jspsych-instructions.js';
import 'jspsych/plugins/jspsych-html-keyboard-response.js';
```
Then handling all the jspsych calls in my `componentDidMount`

This also doesn't break any tests, and all the examples still work fine.

### CODE REVIEW

**Comment by jodeleeuw** [comment]
@RobAWilkinson thanks for getting this process started. I need to learn more about the build tools that (I think) would be required to implement to generate an easy-to-use, node-free experience that closely matches how the current process works. Basically, I don't want to scare off the many people who use jsPsych as their first adventure into JavaScript programming by further complicating how the plugin loading process works from the developer point of view.

**Comment by RobAWilkinson** [comment]
Hi @jodeleeuw, 
Recently updated my fork, I set up  a post install task that will take all the regular normal files we have, copy them, and wrap them in a UMD module definition so they can be required by people who might be using browserify, webpack etc.

I also took the liberty of seperating the code out and moving code that can be tweaked and developed into a `lib` folder, and leaving the `build` folder as the code that is required.

Long term, this will also allow us to possibly add in ES6 features and just build and shim for older browsers that do not support those features yet. 

Would love to get some feedback from you or the other contributors. As it stands now, all the examples in `examples/` work fine, and the entire test suite passes.

I believe we may have to update some of the documentation in order to deal with the code now being in lib. Can we create an issue for updating docs and connect it to this?

**Comment by RobAWilkinson** [comment]
created an issue #529 to help track the work related to this.

**Comment by jodeleeuw** [comment]
Showing my GH ignorance here: Can I modify this PR to create a new branch? I think this is a big enough change that it should happen on a separate branch for now.

**Comment by teonbrooks** [comment]
@jodeleeuw if you add the new branch to the master fork that you want this merged to, you then click the edit button near the title of the PR and redirect the merge to that branch instead

**Comment by RobAWilkinson** [comment]
@teonbrooks thats correct, as long as it is in `lib/plugins/` directory than it should work fine, just remember to import from `build/plugins`.

**Comment by teonbrooks** [comment]
> @teonbrooks thats correct, as long as it is in lib/plugins/ directory than it should work fine, just remember to import from build/plugins.

@RobAWilkinson, just for clarification, say I have my experiment repo, `p300`, 
```
p300
|_ package.json
    files
         |_ experiment.js
            custom_plugin.js
```

and I have my experiment script, `experiment.js`, would I be able to do the following to import a custom plugin:

`experiment.js`
```js
import jspsych from 'jspsych';
import './custom_plugin.js';
```

**Comment by teonbrooks** [comment]
@jdpigeon, this thread might be useful for you

**Comment by jdpigeon** [comment]
Any updates? This would be extremely helpful for the app I'm working on where I'd like to incorporate jsPsych with as little fuss as possible (ideally as a React component that I can just hand experimental details to)

**Comment by teonbrooks** [comment]
@RobAWilkinson, I have a question about the gulp within react components. so, with jspsych standalone, npm install works and the gulp does it thing postinstall. 
I was attempting to update my react component that I made for jspsych but I noticed that if I didn't include gulp at my jspsych-react package level, it wouldn't properly install the jspsych module. 

you mentioned that you got this to work for your react component; do you have to include gulp with your react components or does it work properly for you?

**Comment by jodeleeuw** [comment]
This is being subsumed by the work related to https://github.com/jspsych/jsPsych/projects/6

**Pull request closed without merging**
