### PR TITLE
PR imagepos on canvas within image-keyboard-response

### PR DESCRIPTION
**Pull request by igmmgi**
Option to set canvas size and image position + draw canvas border

### CODE REVIEW

**Comment by becky-gilbert** [comment]
Thanks very much for submitting this improvement to the image-keyboard-response @igmmgi! We'll look at it ASAP 👍

**Comment by becky-gilbert** [comment]
Thanks again - this looks like a really nice addition to the image plugins. 

In order to merge this we'll need to test it, change the image-button-response and image-slider-response plugins to be consistent, and update the docs. Unfortunately we won't have time to do this for v6.3 because we need to finish it up ASAP, so I'm marking this for v7.0.

**Comment by jodeleeuw** [comment]
Bumping this to 7.1 given the complexities of merging into 7.0 directly.

**Comment by jodeleeuw** [comment]
I'm a little worried about the complexities that this would introduce. Right now the `render_on_canvas` feature is meant to be just a background implementation thing. If we add these parameters then they would only work when `render_on_canvas` is true. We could consider implementing the equivalent code for the HTML element version. I think that would be necessary to make this behave intuitively. 

I'm going to close this specific PR since it targets <= 7.0. I've opened an issue #2403 to track this feature request.

**Pull request closed without merging**
