### PR TITLE
added CoC and fixed bug in video-* plugins

### PR DESCRIPTION
**Pull request by becky-gilbert**
Added code-of-conduct.md file to root directory.

### CODE REVIEW

**Comment by becky-gilbert** [comment]
Also:
- Fixed bug in video-* plugins. Data object should record `trial.sources`, not `trial.stimulus` (stimulus parameter doesn't exist).
- Fixed minor formatting issue in the CoC.

Sorry that these are combined. I thought I could make separate PRs for the CoC and video plugins, but now I don't see how to do that.

**Comment by becky-gilbert** [comment]
Josh, do you want me to close this, and then open separate pull requests for the CoC and the video plugin fix?

**Comment by jodeleeuw** [comment]
Hey @becky-gilbert - let's separate this into two PRs just to make issue tracking a bit easier. I think the CoC is ready to merge!

**Comment by becky-gilbert** [comment]
Makes sense! I'm closing this and making a new one for the CoC.

**Pull request closed without merging**
