### PR TITLE
modularization-getters

### PR DESCRIPTION
**Pull request by jodeleeuw**
This prefixes all of the getter methods with `get`

https://github.com/jspsych/jsPsych/projects/6#card-65165145

### CODE REVIEW

**Review by bjoluc — APPROVED** [review]
LGTM!

**Comment by bjoluc** [comment]
@jodeleeuw Would you mind adding a changeset for this to #2066? It's just `npm run chageset` and following the steps there, and possibly editing the markdown file later on.

**Comment by jodeleeuw** [comment]
Alright I think I did this. The only problem is that the link is to #2066 instead of #2100

**Comment by bjoluc** [comment]
Great! Yeah, that's the PR detection of `@changesets/changelog-github` getting in the way in this case. We can override it using the options introduced in [0.3.0](https://github.com/atlassian/changesets/blob/main/packages/changelog-github/CHANGELOG.md#030) (yes, this really seems to be the only place where it's documented...). Luckily, we won't have to touch this later on when changesets are added to PRs directly.

**Pull request merged**
