### PR TITLE
Fix stimulus parameter naming in video response plugins

### PR DESCRIPTION
**Pull request by mgorenstein**
I noticed that video stimuli weren't automatically preloading at the start of experiments with video response plugin trials. 

Per the API documentation, plugin media are preloaded with a call to:
`jsPsych.pluginAPI.registerPreload(plugin_name, parameter, media_type, conditional_function)`

Looking at the video response plugins, the value for `parameter` ("The name of the parameter that is a media file.") was set to 'stimulus', which isn't one of the plugin parameters. 

I replaced 'stimulus' with 'sources' ("The video file to play.") and that fixed the issue.

This PR replaces 'stimulus' with 'sources' in: 
- `jspsych-video-keyboard-response.js`
- `jspsych-video-button-response.js`
- `jspsych-video-slider-response.js`

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Great catch. Dunno how we missed this before. Thanks!

**Comment by jodeleeuw** [comment]
@becky-gilbert we could write a test for this by spying on the preload method and making sure that it is getting called with the right combination of images, video, and audio given a particular timeline. not sure if it is worth it right now. if you think it would be quick to do then go for it.

**Comment by becky-gilbert** [comment]
@jodeleeuw will do! And thanks for catching this @mgorenstein!

**Comment by mgorenstein** [comment]
Of course, glad to help!

**Comment by mgorenstein** [comment]
I pushed another commit making the same change in the `trial_data` object created by those plugins.

**Comment by jodeleeuw** [comment]
Wondering if we should go the other direction, from `sources` to `stimulus`, to maintain consistency with other plugins?

**Comment by becky-gilbert** [comment]
One difference between these video plugins and image/audio plugins is that the stim parameter is an _array_ of one or more files, rather than always a single file, so might be weird to call it `stimulus`. But calling it `stimuli` also seems weird, since it only displays a single video stimulus on each trial.

**Comment by becky-gilbert** [comment]
@mgorenstein we decided to go the other way and call the video stimulus parameter `stimulus` instead of `sources`, mainly for consistency with other plugins. Do you mind updating your pull request? Otherwise I can close this and make the changes myself. 

Thanks again for catching the error! 👍

**Comment by becky-gilbert** [comment]
@mgorenstein fantastic, thank you!

**Comment by mgorenstein** [comment]
Sure! 🦃

**Pull request merged**
