### PR TITLE
Use POST instead of GET mode to submit to MTurk

### PR DESCRIPTION
**Pull request by zimmerrol**
MTurk has a limit on the URL length it processes for GET requests. Therefore, this function can result in a `414 Request URI Too Long` error. This constraint does not exist if we push the data through a POST request to MTurk.

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Thanks @zimmerrol !

I confess that I've stopped using Mechanical Turk for my own work, and so I haven't been keeping close tabs on the `jsPsych.turk` functions. Have you noticed any other issues that we should be tracking with this module?

**Comment by zimmerrol** [comment]
>  Have you noticed any other issues that we should be tracking with this module?
Everything else seems to work fine; at least I have not encountered any other problems.

**Comment by jodeleeuw** [comment]
I think I've broken this PR trying to rebase it onto the current version of `modularization`. I'll merge the changes in via an alternative and link this one in the credits.

**Comment by jodeleeuw** [comment]
These changes were merged via #2121

**Pull request closed without merging**
